name: celeryviz_frontend_core
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_drawing: ^1.0.1
  flutter_bloc: ^8.1.2
  socket_io_client: ^2.0.1
  bloc: ^8.1.1
  equatable: ^2.0.5
  logger: ^1.3.0
  intl: ^0.18.1
  freezed: ^2.3.4
  ndjson: ^0.2.2
  google_fonts: ^5.1.0
  ffi: ^1.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true