name: Dispatch on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger celeryviz_with_lib release workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: bhavya-tech/celeryviz_with_lib
          token: ${{ secrets.PAT }}
          event-type: release-published
          client-payload: '{"tag": "${{ github.ref_name }}"}'
  
      - name: Trigger celeryviz_demo release workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: bhavya-tech/celeryviz_demo
          token: ${{ secrets.PAT }}
          event-type: release-published
